### ISSUE TITLE
No se ven directorios y no autocompleta Failed to perfom operation

### ISSUE THREAD

**Issue by wcadenacasabaca** [JetBrains/pest-intellij#521]
**Describe the bug**
instaldo y desinstalado todo de nuevo, he borrado el contenido de las carpetas:
%APPDATA%\JetBrains\
%LOCALAPPDATA%\JetBrains\
y aun asi sale un mensaje:
![image](https://github.com/JetBrains/pest-intellij/assets/99290876/87fa3e8b-9412-4686-9425-75027fd32961)
y tampoco sirve el autocompletado como isset(), error_log() o die()
**To Reproduce**
1. abrir por primera vex despues de desinstalar todo
2. seleccionar funciones
3. intentar copiar

**Expected behavior**
dejar copiar funciones y autocompletado

**Screenshots**
![image](https://github.com/JetBrains/pest-intellij/assets/99290876/87fa3e8b-9412-4686-9425-75027fd32961)

**Desktop (please complete the following information):**
 - OS: windows 10
 - IntelliJ Version: PHPStorm 2022.3
 - Plugin Version AI Assistent

**Additional context**
```
java.lang.IllegalStateException: Index is not created for `php.pest`
	at com.intellij.util.indexing.FileBasedIndexImpl.getIndex(FileBasedIndexImpl.java:1275)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:293)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:391)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:357)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:1098)
	at com.intellij.util.indexing.FileBasedIndexEx.getValues(FileBasedIndexEx.java:121)
	at com.pestphp.pest.PestUtilKt.isIndexedPestTestFile(PestUtil.kt:29)
	at com.pestphp.pest.PestIconProvider.findIconFromPsiFile(PestIconProvider.kt:20)
	at com.pestphp.pest.PestIconProvider.getIcon(PestIconProvider.kt:16)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.kt:20)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:22)
	at com.intellij.util.IconUtilKt.getProviderIcon(IconUtil.kt:586)
	at com.intellij.util.IconUtilKt.computeFileIconImpl(IconUtil.kt:562)
	at com.intellij.util.IconUtilKt.access$computeFileIconImpl(IconUtil.kt:1)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.kt:149)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$doUpdateFileIcon$icon$1.invoke(EditorsSplitters.kt:399)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$doUpdateFileIcon$icon$1.invoke(EditorsSplitters.kt:398)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:36)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:34)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:310)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:78)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:65)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:44)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:40)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.doUpdateFileIcon$intellij_platform_ide_impl(EditorsSplitters.kt:398)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$iconUpdateChannel$1.invokeSuspend(EditorsSplitters.kt:138)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$iconUpdateChannel$1.invoke(EditorsSplitters.kt)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$iconUpdateChannel$1.invoke(EditorsSplitters.kt)
	at com.intellij.openapi.fileEditor.impl.MergingUpdateChannel.start(MergingUpdateChannel.kt:40)
	at com.intellij.openapi.fileEditor.impl.MergingUpdateChannel$start$1.invokeSuspend(MergingUpdateChannel.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.IllegalStateException: Storage for [C:\Users\wa_cadena\AppData\Local\JetBrains\PhpStorm2023.3\index\php.pest\php.pest.storage] is already registered
	at com.intellij.util.io.FilePageCache.registerPagedFileStorage(FilePageCache.java:410)
	at com.intellij.util.io.PagedFileStorage.<init>(PagedFileStorage.java:72)
	at com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:55)
	at com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:128)
	at com.intellij.util.io.PersistentEnumerator.createDefaultEnumerator(PersistentEnumerator.java:52)
	at com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:165)
	at com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:140)
	at com.intellij.util.indexing.impl.MapIndexStorage.lambda$createPersistentMap$2(MapIndexStorage.java:120)
	at com.intellij.util.io.PersistentHashMapValueStorage$CreationTimeOptions.with(PersistentHashMapValueStorage.java:132)
	at com.intellij.util.indexing.impl.MapIndexStorage.createPersistentMap(MapIndexStorage.java:114)
	at com.intellij.util.indexing.impl.MapIndexStorage.createValueContainerMap(MapIndexStorage.java:126)
	at com.intellij.util.indexing.impl.MapIndexStorage.initMapAndCache(MapIndexStorage.java:72)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapIndexStorage.initMapAndCache(VfsAwareMapIndexStorage.java:60)
	at com.intellij.util.indexing.impl.storage.DefaultIndexStorageLayout$createIndexStorage$1.initMapAndCache(DefaultIndexStorageLayout.kt:79)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapIndexStorage.<init>(VfsAwareMapIndexStorage.java:55)
	at com.intellij.util.indexing.impl.storage.DefaultIndexStorageLayout$createIndexStorage$1.<init>(DefaultIndexStorageLayout.kt:66)
	at com.intellij.util.indexing.impl.storage.DefaultIndexStorageLayout.createIndexStorage(DefaultIndexStorageLayout.kt:66)
	at com.intellij.util.indexing.impl.storage.DefaultIndexStorageLayout$DefaultStorageLayout.openIndexStorage(DefaultIndexStorageLayout.kt:94)
	at com.intellij.util.indexing.impl.storage.TransientFileContentIndex$1.openIndexStorage(TransientFileContentIndex.java:40)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.lambda$new$0(VfsAwareMapReduceIndex.java:59)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:72)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.<init>(MapReduceIndexBase.java:39)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.<init>(VfsAwareMapReduceIndex.java:68)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.<init>(VfsAwareMapReduceIndex.java:58)
	at com.intellij.util.indexing.impl.storage.TransientFileContentIndex.<init>(TransientFileContentIndex.java:36)
	at com.intellij.util.indexing.impl.storage.TransientFileContentIndex.createIndex(TransientFileContentIndex.java:189)
	at com.intellij.util.indexing.FileBasedIndexImpl.createIndex(FileBasedIndexImpl.java:567)
	at com.intellij.util.indexing.FileBasedIndexImpl.initIndexStorage(FileBasedIndexImpl.java:482)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:447)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexDataInitialization.java:88)
	at com.intellij.util.indexing.IndexDataInitializer$Companion.executeTask(IndexDataInitializer.kt:89)
	at com.intellij.util.indexing.IndexDataInitializer$Companion.access$executeTask(IndexDataInitializer.kt:48)
	at com.intellij.util.indexing.IndexDataInitializer$Companion$runParallelTasks$1$1.invokeSuspend(IndexDataInitializer.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	... 4 more
	Suppressed: java.lang.Exception: Storage[C:\Users\wa_cadena\AppData\Local\JetBrains\PhpStorm2023.3\index\php.pest\php.pest.storage] registration stack trace
		at com.intellij.util.io.FilePageCache.registerPagedFileStorage(FilePageCache.java:437)
		... 40 more

```

**Comment by olivernybroe** [comment]
All issues should be reported in YouTrack now. 
Please post it there instead https://youtrack.jetbrains.com/newIssue?project=WI
